services:
  web:
    build:
      context: ..
      dockerfile: docker/DockerfileAPI
    volumes:
      - ../BOOKERY:/app
    command: bash -c "cargo run --bin bookery-api --release"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy
        restart: true
    restart: on-failure

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
